### PR TITLE
Convert floats to strings

### PR DESCRIPTION
**Pull request by preichenberger**

### CODE REVIEW

**Comment by m1kola** [comment]
I'm very new to go, so sorry for a potentially dumb question... As far as I understand the problem in #37 is caused by marshaling from `float64` into `string` with too much precision.

Can't we just define a `MarshalJSON` function that will convert `float64` with like like `fmt.Sprintf("%.8f", amount)`.

As far as I understand, most of the cryptocurrencies need max 8 digits after the decimal point. Price in USD, EUR or GBP need 2 digits `%.2f`.

**Comment by preichenberger** [comment]
There is a general issue of accuracy: https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

**Comment by m1kola** [comment]
Yes, I see. We have two issues here:

* Accuracy of calculations with floats
* Wrong marshaling logic

But we need to think about the solution more carefully. Your changes solve the marshaling issue by making users to perform marshaling. This solves the accuracy issue implicitly by forcing users to perform string parsing. but introduces few other issues. Few from top of my head:

* This change will break backward compatibility;
* You have to support different types to be able to implement very basic things. For example, if you want to maintain a real-time order book with maps for asks and bids (something like `map[KeyType]OrderBookItemType`) and be able to order asks and bids by price you would need to use float as `KeyType` anyway, because you can't use decimals in map keys: you will get duplicates and you can't use strings because `"200.01" > "19999.01" == true`.

I think, this change makes the library harder to use.

I'm looking at min values for currencies supported by GDAX:

```
BTC 0.00000001
LTC 0.00000001
ETH 0.00000001
BCH 0.00000001
EUR 0.01
GBP 0.01
USD 0.01
```

And it seems to me that we can just:
* Implement `MarshalJSON` that will convert floats into strings with required precision. It will solve #37. I can be wrong, but as far as I can see you will not lose anything when you round your float number into `%.8f`. You would need to round a number anyway after calculations.
* Update the documentation to instruct users to use decimals for calculations, if they care about accuracy and convert decimals into floats.

So we use floats only for transport/marshaling purposes. It will be easier to use the library for people who don't care about accuracy much or already use decimals for calculations.

**Comment by phemmer** [comment]
As was stated in #37 ("I chose not to add shopspring's decimal"), it was a deliberate choice not use use a decimal type directly, and instead have the user do the conversion. Just curious, but what's the reasoning behind this? It's rather cumbersome having to manually convert all these values to & from a decimal (or float if that's the user's preference) type.

**Comment by preichenberger** [comment]
Seems like the situation is:
  - Floats are in general dangerous to user's not aware, however they provide a "pleasant" user experience
  - Go's default float marshal does work as expected for floats: https://goplay.space/#Y5e2ED4JFyI so the issue is managing the precision of the floats
  - Using strings in the structs, would be a less "pleasant" user experience and would require the user to manage precision correctly anyway
  - @m1kola's solution is doable, however it adds a good amount of complexity since the marshaler would need to know the context of what currencies are being used. It also will auto-round which doesn't help promote the best practice of float precision

At this point I would prefer to add a very strong warning/recommendation in the readme about float precision and using libs like APD or decimal. This would help promote awareness of the potential issues, while keeping the ease of use of the library. Thoughts?

**Comment by phemmer** [comment]
Another suggestion I might make is to use fixed-point numbers. I use this in a lot of my personal libraries as it's much more performant than decimal.

The basic idea is something like this:

```
type F8 int64
func (f8 *F8) UnmarshalJSON(...) {
  # parse floats (quoted or unquoted) directly into an integer
  # "1.2345" becomes F8(123450000)
}
func (f8 F8) MarshalJSON() {
  # F8(123450000) becomes "1.2345"
}

# convenience functions
func (f8 F8) Float() float64 {
  return float64(f8) / 1e8
}
func Float64ToF8(v float64) F8 {
  return F8(v * 1e8)
}
```

And since `F8` is just an `int64`, it handles @m1kola's issue of using it as a map index.
It also supports native arithmetic operations (e.g. `val := foo - bar`).

There shouldn't be any need to know which currency is in use, as 8 digits after the radix is enough to handle all of them.

**Comment by jonatrey** [comment]
I solved it for orders only in a very simple way, did not create a PR as it's not solving the problem for all the objects:

`diff --git a/order.go b/order.go
index 74a64a7..795a956 100644
--- a/order.go
+++ b/order.go
@@ -4,18 +4,25 @@ import (
 	"fmt"
 )

+type Float float64
+
+// Limit precision of floats to 4 digits when marschalling them to JSON.
+func (n Float) MarshalJSON() ([]byte, error) {
+	return []byte(fmt.Sprintf("%.4f", n)), nil
+}
+
 type Order struct {
-	Type      string  `json:"type"`
-	Size      float64 `json:"size,string,omitempty"`
-	Side      string  `json:"side"`
-	ProductId string  `json:"product_id"`
-	ClientOID string  `json:"client_oid,omitempty"`
-	Stp       string  `json:"stp,omitempty"`
+	Type      string `json:"type"`
+	Size      Float  `json:"size,string,omitempty"`
+	Side      string `json:"side"`
+	ProductId string `json:"product_id"`
+	ClientOID string `json:"client_oid,omitempty"`
+	Stp       string `json:"stp,omitempty"`
 	// Limit Order
-	Price       float64 `json:"price,string,omitempty"`
-	TimeInForce string  `json:"time_in_force,omitempty"`
-	PostOnly    bool    `json:"post_only,omitempty"`
-	CancelAfter string  `json:"cancel_after,omitempty"`
+	Price       Float  `json:"price,string,omitempty"`
+	TimeInForce string `json:"time_in_force,omitempty"`
+	PostOnly    bool   `json:"post_only,omitempty"`
+	CancelAfter string `json:"cancel_after,omitempty"`
 	// Market Order
 	Funds float64 `json:"funds,string,omitempty"`
 	// Response Fields`

And then to use, in a call, just do `gdax.Float(p)` where p is the float64 value.

**Comment by aluzzardi** [comment]
I strongly agree with @preichenberger on this one - using strings and letting users handle conversions is the way to go IMO.

Using floats for monetary values is extremely dangerous. Some solutions proposed here attempt to work around the precision error by wrapping floats but that just hides the problem. At the end of the day it's going to get **silently** either truncated or rounded up.

This is especially dangerous if you're doing operations (e.g. add, multiply) behind the scenes using those values (which I'm guessing most users of this library eventually do?).

`shopspring/decimal` gives some examples of that.
For instance, adding 0.01 a thousand times results in `9.999999999999831` rather than `10`: https://play.golang.org/p/TQBd4yJe6B

I don't see how anyone can perform reliable operations using floats (e.g. place a limit order 10% below the current market price). Strings are the way to go (which is why both CoinBase and GDAX APIs deal with strings, not integers nor floats).

There are a few ways users can deal with that, depending on their particular use case and what they're willing to tolerate:
- Use `big.Rat` (standard library - https://golang.org/pkg/math/big/) to convert from string, do some operations, convert back to a string without silently losing any precision.
- Use a third party library like `shopspring/decimal`
- Use `strconv` or `fmt.Sprintf` if you like to live dangerously

Please do not bake float conversion into the library and try to hide them. Those 15 seconds gained by being more "pleasant" to use will come back and haunt you down the road.

**Comment by chrischris292** [comment]
is it possible to merge this soon? @preichenberger. I was unaware of this issue as I was building off of the go-gdax library and it's caused some headache.

**Pull request merged**
